version: '3'

vars:
  DOCKER_IMAGE: registry.yzguy.net/circleci-runner
  GIT_COMMIT:
    sh: git log -n 1 --format=%h

tasks:
  build:
    desc: Build {{ .DOCKER_IMAGE }}
    cmds:
      - docker build --no-cache -t {{ .DOCKER_IMAGE }}:{{ .GIT_COMMIT }} .

  push:
    desc: Push {{ .DOCKER_IMAGE }}
    cmds:
      - docker push {{ .DOCKER_IMAGE }}:{{ .GIT_COMMIT }}
